language: android
android:
  components:
    - platform-tools
    - tools
    - extra-google-m2repository
    - extra-android-m2repository
    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

before_install:
  - chmod +x gradlew
  
script:
  - TERM=dumb ./gradlew test assembleDebug